name: Example
version: '${project.version}'
main: cn.ng.Example
author: "念国"
softdepend: [PlaceholderAPI]

commands:
  ind:
    permission: ind.admin
  track:
    permission: ind.track
  qx:
    permission: ind.track
permissions:
  ind.admin:
    default: op
  ind.track:
    default: true
  track.accept:
    default: true
  track.deny:
    default: true